### ISSUE TITLE
Limit Note Text Length to Three Lines with Expand Button

### ISSUE THREAD

**Issue by iNikAnn** [iNikAnn/DoHabit#3]
## Description

Implement a restriction on the length of text in the `Note` component so that it does not exceed three lines. If the text exceeds this limit, the `Expand` button should appear at the end of the third line.

**Comment by divitttt** [comment]
CAn I contribute to this

**Comment by iNikAnn** [comment]
> CAn I contribute to this

Yes, you can try to resolve this. Create a separate branch for it and include the issue number in your commit message. Thanks!
@divitttt

**Comment by iNikAnn** [comment]
The text occupies exactly three lines at most, and the "Expand" button is positioned next to other buttons.
